#include "print.h"
#include <stdint.h>

void kernel_main(uint64_t ascii){
    char* kbd_US [128] =
            {
                    '1',
                    '2',
                    '3',
                    '4',
                    '5',
                    '6',
                    '7',
                    '8',
                    '9',
                    '0',
                    '-',
                    '=',
                    ' ',
                    ' ',
                    'Q',
                    'W',
                    'E',
                    'R',
                    'T',
                    'Y',
                    'U',
                    'I',
                    'O',
                    'P',
                    '[',
                    ']',
                    ' ',
                    ' ',
                    'A',
                    'S',
                    'D',
                    'F',
                    'G',
                    'H',
                    'J',
                    'K',
                    'L',
                    ';',
                    ' ',
            '`',
            ' ',
            ' ',
            'Z',
            'X',
            'C',
            'V',
            'B',
            'N',
            'M',
            ',',
            '.',
            '/',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            '-',
            ' ',
            ' ',
            ' ',
            '+',
            ' ',
            ' ',
            ' ',
            ' ',
            ' ',
            };
    uint8_t character = (uint8_t) ascii;
    char str[2] = "";
    str[0] = kbd_US[character-2];
    print_set_color(PRINT_COLOR_BLACK, PRINT_COLOR_WHITE);
    print_str(str);
}

void clear(){
print_clear();
}